DROP TABLE Questions CASCADE CONSTRAINTS;

CREATE TABLE Questions(	
	questionId NUMBER(3) CONSTRAINT Question_id_pk PRIMARY KEY,
	myQ VARCHAR2(30) CONSTRAINT My_Question NOT NULL,
	category VARCHAR(10) CONSTRAINT My_Category NOT NULL
);

INSERT INTO Questions VALUES(1, 'Do you play any sports?', 'Activities');
INSERT INTO Questions VALUES(2, 'Are you part of any clubs?', 'Activities');
INSERT INTO Questions VALUES(3, 'What is your favorite art medium?', 'Activities');
INSERT INTO Questions VALUES(4, 'What is your favorite work of art?', 'Activities');
INSERT INTO Questions VALUES(5, 'What type of dances do you know?', 'Activities');
INSERT INTO Questions VALUES(6, 'If you could learn a new dance, what would it be?', 'Activities');
INSERT INTO Questions VALUES(7, 'What author do you like?', 'Activities');
INSERT INTO Questions VALUES(8, 'What genre of books do you like?', 'Activities');
INSERT INTO Questions VALUES(9, 'What genre of music do you listen to?', 'Activities');
INSERT INTO Questions VALUES(10, 'Any singers/bands you like in particular?', 'Activities');
INSERT INTO Questions VALUES(11, 'Do the songs you listen to change with your mood?', 'Activities');
INSERT INTO Questions VALUES(12, 'If your life had a theme song, what would it be?', 'Activities');
INSERT INTO Questions VALUES(13, 'Do you play any musical instruments?', 'Activities');
INSERT INTO Questions VALUES(14, 'What is your favorite musical instrument to play/listen to?', 'Activities');
INSERT INTO Questions VALUES(15, 'Have you ever been in band/orchestra?', 'Activities');
INSERT INTO Questions VALUES(16, 'Have you ever taken private lessons?', 'Activities');
INSERT INTO Questions VALUES(17, 'Do you prefer brass, strings, or percussion?', 'Activities');
INSERT INTO Questions VALUES(18, 'Do you like country or screamer music?', 'Activities');
INSERT INTO Questions VALUES(19, 'What do you think about ASMR? Do you have a trigger?', 'Activities');
INSERT INTO Questions VALUES(20, 'How many episodes have you binged in 1 day? 1 week?', 'Activities');
INSERT INTO Questions VALUES(21, 'How fast have you gotten through a tv show?', 'Activities');
INSERT INTO Questions VALUES(22, 'What are some actors you think about?', 'Activities');
INSERT INTO Questions VALUES(23, 'Do you think tv shows need more diversity?', 'Activities');
INSERT INTO Questions VALUES(24, 'What would be a killer idea for a tv show?', 'Activities');
INSERT INTO Questions VALUES(25, 'What is something you typically argue about?', 'Arguments');
INSERT INTO Questions VALUES(26, 'When was the last time you had an argument?', 'Arguments');
INSERT INTO Questions VALUES(27, 'What was your last argument about?', 'Arguments');
INSERT INTO Questions VALUES(28, 'Do you regret any arguments?', 'Arguments');
INSERT INTO Questions VALUES(29, 'Are you more passive aggressive or head on?', 'Arguments');
INSERT INTO Questions VALUES(30, 'Have you ever been in a physical fight?', 'Arguments');
INSERT INTO Questions VALUES(31, 'Would you rather be fearless, analytical, smart, or friendly?', 'Choices');
INSERT INTO Questions VALUES(32, 'Which will cause the undoing of society: greedy, cruel, liars, stupid, or fearful?', 'Choices');
INSERT INTO Questions VALUES(33, 'Earth or outer space?', 'Choices');
INSERT INTO Questions VALUES(34, 'If you had to dye your hair, what color would it be?', 'Choices');
INSERT INTO Questions VALUES(35, 'Cats or dogs?', 'Choices');
INSERT INTO Questions VALUES(36, 'Which of the 7 deadly sins fits you best: pride, greed, lust, envy, gluttony, wrath, or sloth?', 'Choices');
INSERT INTO Questions VALUES(37, 'Would you live forever if you had to be ugly?', 'Choices');
INSERT INTO Questions VALUES(38, 'If you could kill one person in the world and get away with it, who would you kill?', 'Choices');
INSERT INTO Questions VALUES(39, 'If you could only eat one type of food for the rest of your life, what would it be?', 'Choices');
INSERT INTO Questions VALUES(40, 'Sweet, salty or spicy? (food)', 'Choices');
INSERT INTO Questions VALUES(41, 'Would you ever get a glucose guardian?', 'Choices');
INSERT INTO Questions VALUES(42, 'Hot or cold?', 'Choices');
INSERT INTO Questions VALUES(43, 'Would you ever bungee jump or sky dive?', 'Choices');
INSERT INTO Questions VALUES(44, 'Would you take your partner''s last name? Would you hyphen it? Would you mash them together?', 'Choices');
INSERT INTO Questions VALUES(45, 'Ketchup all over the french fries, or on the side?', 'Choices');
INSERT INTO Questions VALUES(46, 'Ketchup, mustard, or mayo?', 'Choices');
INSERT INTO Questions VALUES(47, 'You are in last place in MarioKart with no hope of winning. Do you pick blue shell to screw over 1st place or 3 red shells?', 'Choices');
INSERT INTO Questions VALUES(48, 'If person A steals from person B and gives it to person C, is person C obliged to give it back to B, even though they did nothing wrong?', 'Choices');
INSERT INTO Questions VALUES(49, 'Does reverse racism exist?', 'Choices');
INSERT INTO Questions VALUES(50, 'Do descendants of slave owners in the US owe reparations to descendants of slaves?', 'Choices');
INSERT INTO Questions VALUES(51, 'Would you give 100% disease protection to 1 person or 50% to 5 people?', 'Choices');
INSERT INTO Questions VALUES(52, 'Would you break up your best friend to be with the love of your life?', 'Choices');
INSERT INTO Questions VALUES(53, 'Would you live in a virtual machine?', 'Choices');
INSERT INTO Questions VALUES(54, 'How long have you and your partner been together?', 'Couples');
INSERT INTO Questions VALUES(55, 'How did you and your partner get together?', 'Couples');
INSERT INTO Questions VALUES(56, 'Would you ever casually get with someone and not date them?', 'Couples');
INSERT INTO Questions VALUES(57, 'How old/young would you want your sig other to be?', 'Couples');
INSERT INTO Questions VALUES(58, 'What is the oldest/youngest you would date?', 'Couples');
INSERT INTO Questions VALUES(59, 'Would it bug you if your partner didn''t want to hold hands or kiss in public?', 'Couples');
INSERT INTO Questions VALUES(60, 'Would it bug you if your partner didn''t tell their parents about you?', 'Couples');
INSERT INTO Questions VALUES(61, 'What is one word you would use to describe your relationship?', 'Couples');
INSERT INTO Questions VALUES(62, 'Would you ever go on a long distance relationship?', 'Couples');
INSERT INTO Questions VALUES(63, 'Best date you''ve ever been on?', 'Couples');
INSERT INTO Questions VALUES(64, 'Rate significant other's cuteness, 'Couples');
INSERT INTO Questions VALUES(65, 'Could you ever be in a non-emotional relationship? (purely sexual)', 'Couples');
INSERT INTO Questions VALUES(66, 'Would you sleep with a friend if they asked?', 'Couples');
INSERT INTO Questions VALUES(67, 'Have you ever been pushed into something sexual?', 'Couples');
INSERT INTO Questions VALUES(68, 'Have you ever pushed someone into doing something sexual?', 'Couples');
INSERT INTO Questions VALUES(6, 'Have you ever orgasmed?', 'Couples');
INSERT INTO Questions VALUES(70, 'How many times have you orgasmed?', 'Couples');
INSERT INTO Questions VALUES(71, 'Is love an open door?', 'Couples');
INSERT INTO Questions VALUES(72, 'What do your parents think of your sig other?', 'Couples');
INSERT INTO Questions VALUES(73, 'Would you lie to protect your partner''s feelings?', 'Couples');
INSERT INTO Questions VALUES(74, 'How serious are you and your partner?', 'Couples');
INSERT INTO Questions VALUES(75, 'How much of who you are would you be willing to sacrifice for a relationship?', 'Couples');
INSERT INTO Questions VALUES(76, 'Do you like cuddling?', 'Couples');
INSERT INTO Questions VALUES(77, 'What would you do if I were there right now?', 'Couples');
INSERT INTO Questions VALUES(78, 'If we had a threesome, who would you invite?', 'Couples');
INSERT INTO Questions VALUES(79, 'Are you into threesomes?', 'Couples');
INSERT INTO Questions VALUES(80, 'If you had to change one thing about me, what would it be?', 'Couples');
INSERT INTO Questions VALUES(81, 'If someone asked you what I''m like, what would you say?', 'Couples');
INSERT INTO Questions VALUES(82, 'When was the last time you were disappointed with me?', 'Couples');
INSERT INTO Questions VALUES(83, 'What''s your favorite thing about me?', 'Couples');
INSERT INTO Questions VALUES(84, 'Have you ever been mad at me? If so, when and why?', 'Couples');
INSERT INTO Questions VALUES(85, 'How long did you wait before saying I love you? What made you finally say it?', 'Couples');
INSERT INTO Questions VALUES(86, 'If something was bothering me slightly and there was nothing you could do, would you really want to know, knowing it would bug you?', 'Couples');
INSERT INTO Questions VALUES(87, 'Has your partner ever held back? When and why?', 'Couples');
INSERT INTO Questions VALUES(88, 'Have I ever scared you?', 'Couples');
INSERT INTO Questions VALUES(89, 'Do you like the way I smell?', 'Couples');
INSERT INTO Questions VALUES(90, 'Have you ever been mad at your partner? If so, when and why?', 'Couples');
INSERT INTO Questions VALUES(91, 'On a scale from one to ten, how compatible are we?', 'Couples');
INSERT INTO Questions VALUES(92, 'If your partner were the opposite gender, would you still be together?', 'Couples');
INSERT INTO Questions VALUES(93, 'If your partner had opposite genitalia, would you still be together?', 'Couples');
INSERT INTO Questions VALUES(94, 'Would you take your partner''s last name?', 'Couples');
INSERT INTO Questions VALUES(95, 'Have you ever used a toy?', 'Couples');
INSERT INTO Questions VALUES(96, 'How many partners at the same time is too many?', 'Couples');
INSERT INTO Questions VALUES(101, 'Would you prefer a fun, cheap date or splurging?', 'Couples');
INSERT INTO Questions VALUES(102, 'Would you move for love? How far?', 'Couples');
INSERT INTO Questions VALUES(103, 'Does love conquer all?', 'Couples');
INSERT INTO Questions VALUES(104, 'Would you stay with your spouse if you found out they were infertile?', 'Couples');
INSERT INTO Questions VALUES(105, 'What is something you want to know about me?', 'Couples');
INSERT INTO Questions VALUES(106, 'What''s your love language? Words of affirmation, gifts, acts of service, quality time, or physical touch?', 'Couples');
INSERT INTO Questions VALUES(97, 'How many partners in one''s life is too many?', 'Couples');
INSERT INTO Questions VALUES(98, 'Would you prefer to be with a virgin or a more experienced partner?', 'Couples');
INSERT INTO Questions VALUES(99, 'What''s a major turn off for you?', 'Couples');
INSERT INTO Questions VALUES(100, 'Have you ever been with someone who is taller than you(guys) or shorter than you (girls)?', 'Couples');
INSERT INTO Questions VALUES(107, 'Who would be the first to move on after breakup? You or your partner?', 'Couples');
INSERT INTO Questions VALUES(108, 'What was your least favorite/favorite thing about being together?', 'Couples');
INSERT INTO Questions VALUES(109, 'What was something your ex did that bothered you?', 'Couples');
INSERT INTO Questions VALUES(110, 'What was something your partner does that you like?', 'Couples');
INSERT INTO Questions VALUES(111, 'What was the product of your past relationships?', 'Couples');
INSERT INTO Questions VALUES(112, 'Could you ever be friends with your ex?', 'Couples');
INSERT INTO Questions VALUES(113, 'What do you miss most from your past relationships?', 'Couples');
INSERT INTO Questions VALUES(114, 'What did you tell people when they ask why you broke up with your ex?', 'Couples');
INSERT INTO Questions VALUES(115, 'Last time you felt attracted to your ex?', 'Couples');
INSERT INTO Questions VALUES(116, 'Do you feel uncomfortable talking to your ex?', 'Couples');
INSERT INTO Questions VALUES(117, 'Do you still have feelings for your ex?', 'Couples');
INSERT INTO Questions VALUES(118, 'Would you ever get back together with your ex?', 'Couples');
INSERT INTO Questions VALUES(119, 'Do you miss your ex?', 'Couples');
INSERT INTO Questions VALUES(120, 'Most fucked up convo you''ve ever had with an ex?','Couples');
INSERT INTO Questions VALUES(121, 'If you had to hook up with an ex, which ex would it be?', 'Couples');
INSERT INTO Questions VALUES(122, 'What have you learned from your past relationships?', 'Couples');
INSERT INTO Questions VALUES(123, 'Have you ever cheated?', 'Couples');
INSERT INTO Questions VALUES(124, 'Have you ever been cheated on?', 'Couples');
INSERT INTO Questions VALUES(125, 'Have you ever helped somebody else cheat?', 'Couples');
INSERT INTO Questions VALUES(126, 'Have you ever wanted someone you weren''t dating?', 'Couples');
INSERT INTO Questions VALUES(127, 'Would you be okay with causing someone to cheat?', 'Couples');
INSERT INTO Questions VALUES(128, 'Would you ever take back a cheater?', 'Couples');
INSERT INTO Questions VALUES(129, 'Would you tell me if you found out my bf/gf was cheating on me?', 'Couples');
INSERT INTO Questions VALUES(130, 'Have you ever had a crush on one of your friends?', 'Couples');
INSERT INTO Questions VALUES(131, 'How long was your longest crush?', 'Couples');
INSERT INTO Questions VALUES(132, 'How many crushes do you think you have in a year?', 'Couples');
INSERT INTO Questions VALUES(133, 'Do you like a lot of people or not?', 'Couples');
INSERT INTO Questions VALUES(134, 'How many people have ever admitted to liking you?', 'Couples');
INSERT INTO Questions VALUES(135, 'How many people have ever asked you out?', 'Couples');
INSERT INTO Questions VALUES(136, 'Who was your first crush?', 'Couples');
INSERT INTO Questions VALUES(137, 'What do you do to get over a crush?', 'Couples');
INSERT INTO Questions VALUES(138, 'Hottest celebrity?', 'Couples');
INSERT INTO Questions VALUES(139, 'Celebrity crush?', 'Couples');
INSERT INTO Questions VALUES(140, 'Ever been hit on by a cougar/silver fox?', 'Couples');
INSERT INTO Questions VALUES(141, 'What type of person are you attracted to?', 'Couples');
INSERT INTO Questions VALUES(142, 'Could you let your soul mate go for the greater good?', 'Couples');
INSERT INTO Questions VALUES(143, 'Do you prefer younger or older friends?', 'Couples');
INSERT INTO Questions VALUES(144, 'Do you prefer to date someone younger or older?', 'Couples');
INSERT INTO Questions VALUES(145, 'When was the last time you cried?', 'Crying');
INSERT INTO Questions VALUES(146, 'What was the last thing you cried about?', 'Crying');
INSERT INTO Questions VALUES(147, 'What do you typically cry about?', 'Crying');
INSERT INTO Questions VALUES(148, 'How often do you cry?', 'Crying');
INSERT INTO Questions VALUES(149, 'Have you ever made anyone cry?', 'Crying');
INSERT INTO Questions VALUES(150, 'Have you ever cried after sex?', 'Crying');
INSERT INTO Questions VALUES(151, 'What do you typically dream about?', 'Dreams');
INSERT INTO Questions VALUES(152, 'Who do you see most in your dreams?', 'Dreams');
INSERT INTO Questions VALUES(153, 'Where do your dreams typically take place?', 'Dreams');
INSERT INTO Questions VALUES(154, 'Do you ever dream about flying?', 'Dreams');
INSERT INTO Questions VALUES(155, 'What was your scariest dream?', 'Dreams');
INSERT INTO Questions VALUES(156, 'What was your weirdest dream?', 'Dreams');
INSERT INTO Questions VALUES(157, 'What is the earliest dream you can remember?', 'Dreams');
INSERT INTO Questions VALUES(158, 'What''s an interesting dream you''ve had recently?', 'Dreams');
INSERT INTO Questions VALUES(159, 'What do you daydream about?', 'Dreams');
INSERT INTO Questions VALUES(160, 'What are some goals you have for the next month? Next year? Next 10 years?', 'Dreams');
INSERT INTO Questions VALUES(161, 'Do you have stress dreams? (teeth falling out, being chased/stalked, falling)', 'Dreams');
INSERT INTO Questions VALUES(162, 'Do you ever have repeat dreams?', 'Dreams');
INSERT INTO Questions VALUES(163, 'What is the most you''ve ever taken/dranken at one time?', 'Drugs');
INSERT INTO Questions VALUES(164, 'When did you start drinking/taking drugs?', 'Drugs');
INSERT INTO Questions VALUES(165, 'Have you ever helped a friend with a crisis while they/you were drunk/high?', 'Drugs');
INSERT INTO Questions VALUES(166, 'Have you ever hallucinated?', 'Drugs');
INSERT INTO Questions VALUES(167, 'Have you ever faked sobriety?', 'Drugs');
INSERT INTO Questions VALUES(168, 'Do you typically take drugs/drink?', 'Drugs');
INSERT INTO Questions VALUES(169, 'Have you ever done something stupid while drunk/high?', 'Drugs');
INSERT INTO Questions VALUES(170, 'What''s the hardest drug you''ve ever taken?', 'Drugs');
INSERT INTO Questions VALUES(171, 'Have you ever gotten drunk and high at the same time?', 'Drugs');
INSERT INTO Questions VALUES(172, 'Have you ever sold drugs?', 'Drugs');
INSERT INTO Questions VALUES(173, 'What is something that runs in the family?', 'Family');
INSERT INTO Questions VALUES(174, 'Which of your (grand)parents are you most similar to?', 'Family');
INSERT INTO Questions VALUES(175, 'What does your family think of mixed-race marriages?', 'Family');
INSERT INTO Questions VALUES(176, 'Who celebrates holidays with you? How do you celebrate?', 'Family');
INSERT INTO Questions VALUES(177, 'Where is your family from?', 'Family');
INSERT INTO Questions VALUES(178, 'What are some traditions that your family has?', 'Family');
INSERT INTO Questions VALUES(179, 'Tell me about your family', 'Family');
INSERT INTO Questions VALUES(180, 'Best looking cousin/sibling', 'Family');
INSERT INTO Questions VALUES(181, 'What does your family think of gay marriages?', 'Family');
INSERT INTO Questions VALUES(182, 'Do you prefer mom or dad? (or parent 1 or parent 2)', 'Family');
INSERT INTO Questions VALUES(183, 'What age do you want to get married at?', 'Family');
INSERT INTO Questions VALUES(184, 'At what age do you want to have kids?', 'Family');
INSERT INTO Questions VALUES(185, 'How old will your kids be when you let them drink/have sex?', 'Family');
INSERT INTO Questions VALUES(186, 'How do you think you would be as a parent?', 'Family');
INSERT INTO Questions VALUES(187, 'What do you want to do differently from your own parent(s)?', 'Family');
INSERT INTO Questions VALUES(188, 'What do you appreciate about the way your parent(s) raised you?', 'Family');
INSERT INTO Questions VALUES(189, 'Favorite color?', 'Favorites');
INSERT INTO Questions VALUES(190, 'Favorite book?', 'Favorites');
INSERT INTO Questions VALUES(191, 'Favorite tv show?', 'Favorites');
INSERT INTO Questions VALUES(192, 'Favorite movie?', 'Favorites');
INSERT INTO Questions VALUES(193, 'Favorite word?', 'Favorites');
INSERT INTO Questions VALUES(194, 'Favorite language?', 'Favorites');
INSERT INTO Questions VALUES(195, 'Favorite person? (role model)', 'Favorites');
INSERT INTO Questions VALUES(196, 'Favorite music?', 'Favorites');
INSERT INTO Questions VALUES(197, 'Favorite animal?', 'Favorites');
INSERT INTO Questions VALUES(198, 'Favorite season?', 'Favorites');
INSERT INTO Questions VALUES(199, 'Favorite pokemon?', 'Favorites');
INSERT INTO Questions VALUES(200, 'Favorite smell?', 'Favorites');
INSERT INTO Questions VALUES(201, 'Favorite type/piece of clothing', 'Favorites');
INSERT INTO Questions VALUES(202, 'Have you ever licked a vehicle?', 'Food');
INSERT INTO Questions VALUES(203, 'If a person consented to having their body used for this purpose before they died, would you try human meat?', 'Food');
INSERT INTO Questions VALUES(204, 'Could you kill + eat an animal you owned?', 'Food');
INSERT INTO Questions VALUES(205, 'Weirdest thing you''ve put in your mouth?', 'Food');
INSERT INTO Questions VALUES(206, 'Weirdest food you''ve tried?', 'Food');
INSERT INTO Questions VALUES(207, 'How do you like your eggs?', 'Food');
INSERT INTO Questions VALUES(208, 'What is your favorite candy?', 'Food');
INSERT INTO Questions VALUES(209, 'Favorite part of the food pyramid? Sugar, fats, meat, dairy, grains, fruit, or vegetables?', 'Food');
INSERT INTO Questions VALUES(210, 'Are you on a diet?', 'Food');
INSERT INTO Questions VALUES(211, 'Have you ever been on a diet?', 'Food');
INSERT INTO Questions VALUES(212, 'Who is your best friend?', 'Friends');
INSERT INTO Questions VALUES(213, 'How did your best friend become your best friend?', 'Friends');
INSERT INTO Questions VALUES(214, 'What kind of people do you typically try to hang out with?', 'Friends');
INSERT INTO Questions VALUES(215, 'What kind of people do you typically try to hang out avoid?', 'Friends');
INSERT INTO Questions VALUES(216, 'What is an attribute that will cause you to lose a friend?', 'Friends');
INSERT INTO Questions VALUES(217, 'Which friends do you prefer, guys or girls?', 'Friends');
INSERT INTO Questions VALUES(218, 'What do you think people think of you?', 'Friends');
INSERT INTO Questions VALUES(219, 'What''s the worst personality trait a person could have?', 'Friends');
INSERT INTO Questions VALUES(220, 'How many friends have you cut out of your life purposely?', 'Friends');
INSERT INTO Questions VALUES(221, 'Do you have any pity friends?', 'Friends');
INSERT INTO Questions VALUES(222, 'What is something you have done that all your friends haven''t?', 'Friends');
INSERT INTO Questions VALUES(223, 'What is something all your friends have done that you haven''t?', 'Friends');
INSERT INTO Questions VALUES(224, 'Have you ever lied to your friends?', 'Friends');
INSERT INTO Questions VALUES(225, 'How do you describe me to your other friends?', 'Friends');
INSERT INTO Questions VALUES(226, 'What''s the weirdest place you''ve made a friend?', 'Friends');
INSERT INTO Questions VALUES(227, 'Do I pass the delayed airplane test? You would keep in contact with me after talking together on a delayed airplane?', 'Friends');
INSERT INTO Questions VALUES(228, 'How many friends are in your core group of friends?', 'Friends');
INSERT INTO Questions VALUES(229, 'Ideal roommate?', 'Friends');
INSERT INTO Questions VALUES(230, 'Roommate horror stories?', 'Friends');
INSERT INTO Questions VALUES(231, 'Best roommate?', 'Friends');
INSERT INTO Questions VALUES(232, 'Worst roommate?', 'Friends');
INSERT INTO Questions VALUES(233, 'Have you ever shared a room with your siblings?', 'Family');
INSERT INTO Questions VALUES(234, 'What do you hope to do (job-wise) with your future?', 'Future');
INSERT INTO Questions VALUES(235, 'Do you intend to travel a lot when you grow up?', 'Future');
INSERT INTO Questions VALUES(236, 'What is your dream job?', 'Future');
INSERT INTO Questions VALUES(237, 'Do you plan on getting married/having kids?', 'Future');
INSERT INTO Questions VALUES(238, 'Do you plan on owning pets?', 'Future');
INSERT INTO Questions VALUES(239, 'Do you plan on having kids?', 'Future');
INSERT INTO Questions VALUES(240, 'How many kids do you want to have?', 'Future');
INSERT INTO Questions VALUES(241, 'What medicine are you on?', 'Health');
INSERT INTO Questions VALUES(242, 'Pro-vax or pro-choice?', 'Health');
INSERT INTO Questions VALUES(243, 'Pro-life or pro-choice?', 'Health');
INSERT INTO Questions VALUES(244, 'Worst medical crisis you''ve had?', 'Health');
INSERT INTO Questions VALUES(245, 'Have you ever broken a bone?', 'Health');
INSERT INTO Questions VALUES(246, 'Would you rather live as a vegetable or have the plug pulled?', 'Health');
INSERT INTO Questions VALUES(247, 'Worst sunburn you''ve ever had?', 'Health');
INSERT INTO Questions VALUES(248, 'Thoughts on organ donation?', 'Health');
INSERT INTO Questions VALUES(249, 'If you could eradicate 1 world disease, which one would it be?', 'Health');
INSERT INTO Questions VALUES(250, 'Do you have wisdom teeth?', 'Health');
INSERT INTO Questions VALUES(251, 'Have you ever fainted?', 'Health');
INSERT INTO Questions VALUES(252, 'Do you have a chronic illness? This includes asthma & ADHD', 'Health');
INSERT INTO Questions VALUES(253, 'What language would you like to learn?', 'Languages');
INSERT INTO Questions VALUES(254, 'What language do you speak best?', 'Languages');
INSERT INTO Questions VALUES(255, 'What is your favorite language that you know?', 'Languages');
INSERT INTO Questions VALUES(256, 'Do you switch languages depending on the circumstances?', 'Languages');
INSERT INTO Questions VALUES(257, 'How did you learn your languages?', 'Languages');
INSERT INTO Questions VALUES(258, 'Thoughts on Esperanto, the language to unite all nations as a neutral language?', 'Languages');
INSERT INTO Questions VALUES(259, 'Are you fluent in any second language? Are you conversational?', 'Languages');
INSERT INTO Questions VALUES(260, 'Would you ever learn a dying language?', 'Languages');
INSERT INTO Questions VALUES(261, 'Favorite language family?', 'Languages');
INSERT INTO Questions VALUES(262, 'What should be the world language to communicate?', 'Languages');
INSERT INTO Questions VALUES(263, 'Should everyone just learn English?', 'Languages');
INSERT INTO Questions VALUES(264, 'If you had to, could you speak in a foreign language all day to get by?', 'Languages');
INSERT INTO Questions VALUES(265, 'Is sexy talk in other languages hot or confusing?', 'Languages');
INSERT INTO Questions VALUES(266, 'Which languages are more sexy?', 'Languages');
INSERT INTO Questions VALUES(267, 'Which languages are more scary?', 'Languages');
INSERT INTO Questions VALUES(268, 'Have you ever been with someone of the same sex?', 'LGBT+');
INSERT INTO Questions VALUES(269, 'What is the farthest you would ever go with someone of the same sex?', 'LGBT+');
INSERT INTO Questions VALUES(270, 'Do you have a sexual preference for guys or girls?', 'LGBT+');
INSERT INTO Questions VALUES(271, 'Femme or butch? (self or other)', 'LGBT+');
INSERT INTO Questions VALUES(272, 'Have you ever had thoughts about the same sex?', 'LGBT+');
INSERT INTO Questions VALUES(273, 'What do you want the gender of your next partner to be?', 'LGBT+');
INSERT INTO Questions VALUES(274, 'Have you ever considered/played around with the idea of being the opposite sex?', 'LGBT+');
INSERT INTO Questions VALUES(275, 'Opinion on trans-species-ists', 'LGBT+');
INSERT INTO Questions VALUES(276, 'Would you date someone who is LGBT+?', 'LGBT+');
INSERT INTO Questions VALUES(277, 'How do you feel about your own sexuality?', 'LGBT+
');
INSERT INTO Questions VALUES(278, 'Do you believe sexualities can change?', 'LGBT+');
INSERT INTO Questions VALUES(279, 'Do you believe genders can change?', 'LGBT+');
INSERT INTO Questions VALUES(280, 'Who are better kissers, guys or girls?', 'LGBT+');
INSERT INTO Questions VALUES(281, 'What''s the craziest thing you''ve ever seen?', 'Memories');
INSERT INTO Questions VALUES(282, 'What is the oldest/first memory you have?', 'Memories');
INSERT INTO Questions VALUES(283, 'What is the best gift you have ever received?', 'Memories');
INSERT INTO Questions VALUES(284, 'What was prom like?', 'Memories');
INSERT INTO Questions VALUES(285, 'First day of school?', 'Memories');
INSERT INTO Questions VALUES(286, 'First impression of me?', 'Memories');
INSERT INTO Questions VALUES(287, 'Worst decision you ever made?', 'Memories');
INSERT INTO Questions VALUES(288, 'Craziest dare you''ve ever done?', 'Memories');
INSERT INTO Questions VALUES(289, 'Weirdest memory?', 'Memories');
INSERT INTO Questions VALUES(290, 'Funniest memory?', 'Memories');
INSERT INTO Questions VALUES(291, 'What''s the worst thing you''ve ever done?', 'Memories');
INSERT INTO Questions VALUES(292, 'Have you ever broken the law?', 'Memories');
INSERT INTO Questions VALUES(293, 'What''s the most embarrassing thing you''ve ever posted on social media?', 'Memories');
INSERT INTO Questions VALUES(294, 'What''s the most embarrassing thing you''ve ever been caught doing?', 'Memories');
INSERT INTO Questions VALUES(295, 'What is the worst thing you''ve ever done?', 'Memories');
INSERT INTO Questions VALUES(296, 'Have you ever killed anything?', 'Memories');
INSERT INTO Questions VALUES(297, 'Has something ever happened because of this game?', 'Memories');
INSERT INTO Questions VALUES(298, 'What''s the most painful thing you''ve ever had to do?', 'Memories');
INSERT INTO Questions VALUES(299, 'Worst teacher you''ve ever had?', 'Memories');
INSERT INTO Questions VALUES(300, 'Best teacher you''ve ever had?', 'Memories');
INSERT INTO Questions VALUES(301, 'Have you ever been treated poorly by a partner?', 'Memories');
INSERT INTO Questions VALUES(302, 'What''s your favorite article of clothing, and a story you have about it', 'Memories');
INSERT INTO Questions VALUES(303, 'Ever gone to a concert?', 'Memories');
INSERT INTO Questions VALUES(304, 'Ever scuba dove?', 'Memories');
INSERT INTO Questions VALUES(305, 'Earliest memory you have?', 'Memories');
INSERT INTO Questions VALUES(306, 'How old were you when you dropped your first F-bomb?', 'Memories');
INSERT INTO Questions VALUES(307, 'Where were you during 9-11?', 'Memories');
INSERT INTO Questions VALUES(308, 'How many times have you moved?', 'Memories');
INSERT INTO Questions VALUES(309, 'What details are you the best at noticing or remembering?', 'Memories');
INSERT INTO Questions VALUES(310, 'What details do you always forget or never pick up on?', 'Memories');
INSERT INTO Questions VALUES(311, 'What is a moment when you felt helpless and vulnerable?', 'Memories');
INSERT INTO Questions VALUES(312, 'At what age did you really start to get into your passion?', 'Memories');
INSERT INTO Questions VALUES(313, 'What''s your favorite thing about your passion?', 'Memories');
INSERT INTO Questions VALUES(314, 'Weirdest name you''ve ever heard?', 'Memories');
INSERT INTO Questions VALUES(315, 'What does your name mean?', 'Memories');
INSERT INTO Questions VALUES(316, 'If you were opposite gender, what would your name be?', 'Memories');
INSERT INTO Questions VALUES(317, 'If you had to pick a new name, what would it be?', 'Memories');
INSERT INTO Questions VALUES(318, 'What were some other babyname choices your parents had for you?', 'Memories');
INSERT INTO Questions VALUES(319, 'Do you have names in any other languages?', 'Memories');
INSERT INTO Questions VALUES(320, 'Would you ever join a frat?', 'Partying');
INSERT INTO Questions VALUES(321, 'What is your ideal type of party?', 'Partying');
INSERT INTO Questions VALUES(322, 'What''s the most number of nights you''ve gone partying in a row?', 'Partying');
INSERT INTO Questions VALUES(323, 'What''s the latest you''ve stayed out at a party?', 'Partying');
INSERT INTO Questions VALUES(324, 'Would you ever get hazed?', 'Partying');
INSERT INTO Questions VALUES(325, 'Have you ever hazed someone?', 'Partying');
INSERT INTO Questions VALUES(326, 'Thoughts on the death penalty?', 'Politics');
INSERT INTO Questions VALUES(327, 'Thoughts on immigration?', 'Politics');
INSERT INTO Questions VALUES(328, 'Conservative or liberal?', 'Politics');
INSERT INTO Questions VALUES(329, 'Republican or Democrat?', 'Politics');
INSERT INTO Questions VALUES(330, 'Is socialism a good thing?', 'Politics');
INSERT INTO Questions VALUES(331, 'Is capitalism a good thing?', 'Politics');
INSERT INTO Questions VALUES(332, 'Is consumerism a good thing?', 'Politics');
INSERT INTO Questions VALUES(333, 'Is the free market a good thing?', 'Politics');
INSERT INTO Questions VALUES(334, 'Higher taxes to help the poor or lower taxes to support oneself?', 'Politics');
INSERT INTO Questions VALUES(335, 'Thoughts on abortion?', 'Politics');
INSERT INTO Questions VALUES(336, 'What is one thing you regret in life?', 'Regrets');
INSERT INTO Questions VALUES(337, 'What do you regret about hs?', 'Regrets');
INSERT INTO Questions VALUES(338, 'Do you have any regrets?', 'Regrets');
INSERT INTO Questions VALUES(339, 'Do you regret choosing the college you did?', 'Regrets');
INSERT INTO Questions VALUES(340, 'Do you regret choosing the career path you did?', 'Regrets');
INSERT INTO Questions VALUES(341, 'Do you believe in religion or spirituality?', 'Religions');
INSERT INTO Questions VALUES(342, 'How religious are you?', 'Religions');
INSERT INTO Questions VALUES(343, 'Do you celebrate holidays with your family?', 'Religions');
INSERT INTO Questions VALUES(344, 'What comes after death?', 'Religions');
INSERT INTO Questions VALUES(345, 'What comes before life?', 'Religions');
INSERT INTO Questions VALUES(346, 'Do you believe in any “conspiracy theories”?', 'Religions');
INSERT INTO Questions VALUES(347, 'Would you change your religion for your significant other?', 'Religions');
INSERT INTO Questions VALUES(348, 'Do you want your significant other to have the same religion as you? If not, how do you justify dating people of different religions?', 'Religions');
INSERT INTO Questions VALUES(349, 'Are animals less than or equal to humans?', 'Religions');
INSERT INTO Questions VALUES(350, 'If Satan is the biggest sinner out there, why do we not pray for him?', 'Religions');
INSERT INTO Questions VALUES(351, 'What''s the hardest class you''ve ever taken?', 'School');
INSERT INTO Questions VALUES(352, 'How many classes do you typically take?', 'School');
INSERT INTO Questions VALUES(353, 'What was the most amount of credits you''ve ever taken?', 'School');
INSERT INTO Questions VALUES(354, 'What is a class that you would recommend?', 'School');
INSERT INTO Questions VALUES(355, 'What is a tradition at your school that you do not follow?', 'School');
INSERT INTO Questions VALUES(356, 'Would you ever consider sitting for the pledge of allegiance?', 'School');
INSERT INTO Questions VALUES(357, 'What''s the highest degree you want to get?', 'School');
INSERT INTO Questions VALUES(358, 'How does your major affect your worldviews?', 'School');
INSERT INTO Questions VALUES(359, 'How would you characterize the attributes of a person in your major?', 'School');
INSERT INTO Questions VALUES(360, 'Good hazing stories?', 'School');
INSERT INTO Questions VALUES(361, 'Most memorable all nighter?', 'School');
INSERT INTO Questions VALUES(362, 'What made you the person you are today?', 'Self');
INSERT INTO Questions VALUES(363, 'What was your childhood like?', 'Self');
INSERT INTO Questions VALUES(364, 'What is your favorite aspect about yourself?', 'Self');
INSERT INTO Questions VALUES(365, 'What is your least favorite aspect about yourself?', 'Self');
INSERT INTO Questions VALUES(366, 'What is your greatest accomplishment?', 'Self');
INSERT INTO Questions VALUES(367, 'Do you see yourself as stressed or laid back?', 'Self');
INSERT INTO Questions VALUES(368, 'Are you organized?', 'Self');
INSERT INTO Questions VALUES(369, 'Are you a dreamer or a doer?', 'Self');
INSERT INTO Questions VALUES(370, 'How long do you like to shower?', 'Self');
INSERT INTO Questions VALUES(371, 'Fancy or casual?', 'Self');
INSERT INTO Questions VALUES(372, 'Makeup or nah?', 'Self');
INSERT INTO Questions VALUES(373, 'What is something I don''t know about you?', 'Self');
INSERT INTO Questions VALUES(374, 'If you had to change something about yourself, what would you change?', 'Self');
INSERT INTO Questions VALUES(375, 'What is something you need to improve on?', 'Self');
INSERT INTO Questions VALUES(376, 'Do you have any fears?', 'Self');
INSERT INTO Questions VALUES(377, 'What is your biggest fear?', 'Self');
INSERT INTO Questions VALUES(378, 'Do you want to live close to or far from home?', 'Self');
INSERT INTO Questions VALUES(379, 'What are 5 things that you like?', 'Self');
INSERT INTO Questions VALUES(380, 'What are 5 things that you don''t like?', 'Self');
INSERT INTO Questions VALUES(381, 'What is the best case scenario for your life?', 'Self');
INSERT INTO Questions VALUES(382, 'What is the worst case scenario for your life?', 'Self');
INSERT INTO Questions VALUES(383, 'How often do you lie?', 'Self');
INSERT INTO Questions VALUES(384, 'What do you secretly like but pretend you don''t?', 'Self');
INSERT INTO Questions VALUES(385, 'What is something you think about but don''t say?', 'Self');
INSERT INTO Questions VALUES(386, 'How do you keep goals?', 'Self');
INSERT INTO Questions VALUES(387, 'When do you feel the most beautiful?', 'Self');
INSERT INTO Questions VALUES(388, 'How do you measure wealth?', 'Self');
INSERT INTO Questions VALUES(389, 'Opinion on feminism?', 'Politics');
INSERT INTO Questions VALUES(390, 'Opinion on war?', 'Politics');
INSERT INTO Questions VALUES(391, 'Opinion on climate change?', 'Politics');
INSERT INTO Questions VALUES(392, 'Opinion on the flat-earth controversy?', 'Politics');
INSERT INTO Questions VALUES(393, 'Opinion on dinosaurs?', 'Self');
INSERT INTO Questions VALUES(394, 'What do you want to do before you die?', 'Self');
INSERT INTO Questions VALUES(395, 'What would cause you to finally snap and start murdering people?', 'Self');
INSERT INTO Questions VALUES(396, 'What do you want to do with your body after you die?', 'Self');
INSERT INTO Questions VALUES(397, 'What is something that would completely ruin your day?', 'Self');
INSERT INTO Questions VALUES(398, 'Do you believe in second chances?', 'Self');
INSERT INTO Questions VALUES(399, 'Are you confrontational?', 'Self');
INSERT INTO Questions VALUES(400, 'Do you ever feel confined by your culture (in expressing feelings, in gender bending, etc)', 'Self');
INSERT INTO Questions VALUES(401, 'How long should you wait before you have sex with someone?', 'Sexual');
INSERT INTO Questions VALUES(402, 'What''s the farthest you''ve ever gone with someone?', 'Sexual');
INSERT INTO Questions VALUES(403, 'How far would you go with someone you weren''t dating?', 'Sexual');
INSERT INTO Questions VALUES(404, 'Fav sex position?', 'Sexual');
INSERT INTO Questions VALUES(405, 'Sexual fantasy?', 'Sexual');
INSERT INTO Questions VALUES(406, 'Have you ever walked in on someone?', 'Sexual');
INSERT INTO Questions VALUES(407, 'Favorite letter: BD, DS, SM?', 'Sexual');
INSERT INTO Questions VALUES(408, 'Dom or sub (or switch)?', 'Sexual');
INSERT INTO Questions VALUES(409, 'Have you ever read 50 shades of gray, or seen the movie?', 'Sexual');
INSERT INTO Questions VALUES(410, 'Weirdest place you''ve ever gotten a hickey?', 'Sexual');
INSERT INTO Questions VALUES(411, 'Have you ever had an orgy?', 'Sexual');
INSERT INTO Questions VALUES(412, 'Have you ever had a pregnancy scare?', 'Sexual');
INSERT INTO Questions VALUES(413, 'Do you have any fetishes?', 'Sexual');
INSERT INTO Questions VALUES(414, 'Do you play music during sex?', 'Sexual');
INSERT INTO Questions VALUES(415, 'Have you ever caused/gotten blue balls?', 'Sexual');
INSERT INTO Questions VALUES(416, 'Have you ever given someone false hope?', 'Sexual');
INSERT INTO Questions VALUES(417, 'Have you ever flirted to get out of something?', 'Sexual');
INSERT INTO Questions VALUES(418, 'Tits or ass?', 'Sexual');
INSERT INTO Questions VALUES(419, 'How horny are you right now?', 'Sexual');
INSERT INTO Questions VALUES(420, 'Most obscure sexual action you''ve ever heard of?', 'Sexual');
INSERT INTO Questions VALUES(421, 'What color is your underwear?', 'Sexual');
INSERT INTO Questions VALUES(422, 'What is something you would feel uncomfortable doing?', 'Sexual');
INSERT INTO Questions VALUES(423, 'What''s the craziest thing you''ve done naked?', 'Sexual');
INSERT INTO Questions VALUES(424, 'What is one of the more sensitive areas of your body?', 'Sexual');
INSERT INTO Questions VALUES(425, 'What is a public place you would do oral?', 'Sexual');
INSERT INTO Questions VALUES(426, 'Most ticklish place on your body?', 'Sexual');
INSERT INTO Questions VALUES(427, 'Have you ever been offered a one night stand? Did you do it?', 'Sexual');
INSERT INTO Questions VALUES(428, 'If you had to be with someone outside your race, would you pick: white, black, asian, latina, native american, mixed?', 'Sexual');
INSERT INTO Questions VALUES(429, 'Would you ever eat ass/get your ass eaten out?', 'Sexual');
INSERT INTO Questions VALUES(430, 'Have you ever skinny dipped?', 'Sexual');
INSERT INTO Questions VALUES(431, 'Are ears sexual?', 'Sexual');
INSERT INTO Questions VALUES(432, 'Are you into role playing?', 'Sexual');
INSERT INTO Questions VALUES(433, 'Have you/your partner ever squirted?', 'Sexual');
INSERT INTO Questions VALUES(434, 'Do you like doing buttstuff?', 'Sexual');
INSERT INTO Questions VALUES(435, 'How old were you when you first bought condoms?', 'Sexual');
INSERT INTO Questions VALUES(436, 'Would you date someone who was bi or pan?', 'Sexual');
INSERT INTO Questions VALUES(437, 'Would you date someone who was asexual?', 'Sexual');
INSERT INTO Questions VALUES(438, 'Would you date someone who was trans?', 'Sexual');
INSERT INTO Questions VALUES(439, 'Would you date someone who was poly?', 'Sexual');
INSERT INTO Questions VALUES(440, 'Would you date someone who was sapiosexual?', 'Sexual');
INSERT INTO Questions VALUES(441, 'Have you ever had/given clitoral orgasm? Vaginal orgasm? Both at the same time?', 'Sexual');
INSERT INTO Questions VALUES(442, 'What do you think of the taste of cum?', 'Sexual');
INSERT INTO Questions VALUES(443, 'Are you messy?', 'Sexual');
INSERT INTO Questions VALUES(444, 'How long after you started going out with someone did you decide to have sex for the first time?', 'Sexual');
INSERT INTO Questions VALUES(445, 'Lights on or lights off?', 'Sexual');
INSERT INTO Questions VALUES(446, 'Would you fuck someone with no brains just because they are pretty?', 'Sexual');
INSERT INTO Questions VALUES(447, 'Would you fuck someone you met that day? Or that week?', 'Sexual');
INSERT INTO Questions VALUES(448, 'Have you/would you ever hate-fuck someone?', 'Sexual');
INSERT INTO Questions VALUES(449, 'If you were going to have sex a balcony, at what floor would you feel comfortable? Yes, people can see through the handrails', 'Sexual');
INSERT INTO Questions VALUES(450, 'Pet names? Names in bed?', 'Sexual');
INSERT INTO Questions VALUES(451, 'Ever been called the wrong name in bed?', 'Sexual');
INSERT INTO Questions VALUES(452, 'Do you like getting balls fondled/ fondling balls?', 'Sexual');
INSERT INTO Questions VALUES(453, 'Music during sex?', 'Sexual');
INSERT INTO Questions VALUES(454, 'Craziest sexual act you''ve done in public?', 'Sexual');
INSERT INTO Questions VALUES(455, 'Socks on or off during sex?', 'Sexual');
INSERT INTO Questions VALUES(456, 'Lights on or off during sex?', 'Sexual');
INSERT INTO Questions VALUES(457, 'Over or under covers during sex?', 'Sexual');
INSERT INTO Questions VALUES(458, 'Food in the bedroom?', 'Sexual');
INSERT INTO Questions VALUES(459, 'Ever finish in someone/ been finished in?', 'Sexual');
INSERT INTO Questions VALUES(460, 'Most number of fingers you can take/have ever given?', 'Sexual');
INSERT INTO Questions VALUES(461, 'Ever stuck a ball into her?', 'Sexual');
INSERT INTO Questions VALUES(462, 'Ever done car sex?', 'Sexual');
INSERT INTO Questions VALUES(463, 'Ever done shower sex?', 'Sexual');
INSERT INTO Questions VALUES(464, 'Ever done cybersex?', 'Sexual');
INSERT INTO Questions VALUES(465, 'Hentai???', 'Sexual');
INSERT INTO Questions VALUES(466, 'Most number of nights having sex in a row?', 'Sexual');
INSERT INTO Questions VALUES(467, 'Ever been hit with a dick?', 'Sexual');
INSERT INTO Questions VALUES(468, 'Spit or swallow?', 'Sexual');
INSERT INTO Questions VALUES(469, 'Do you read smut?', 'Sexual');
INSERT INTO Questions VALUES(470, 'Turn offs?', 'Sexual');
INSERT INTO Questions VALUES(471, 'Turn ons?', 'Sexual');
INSERT INTO Questions VALUES(472, 'Girls: Most number of times you''ve ever orgasmed in a row?', 'Sexual');
INSERT INTO Questions VALUES(473, 'Boys: How long do you typically have to wait before another orgasm? How short is the shortest amount of time you''ve had to wait?', 'Sexual');
INSERT INTO Questions VALUES(474, 'Dream place to have sex?', 'Sexual');
INSERT INTO Questions VALUES(475, 'Lip biting?', 'Sexual');
INSERT INTO Questions VALUES(476, 'If you had to fuck Trump to save America, would you do it?', 'Sexual');
INSERT INTO Questions VALUES(477, 'When was the last time you had sex?', 'Sexual');
INSERT INTO Questions VALUES(478, 'How many fingers can you fit in you?', 'Sexual');
INSERT INTO Questions VALUES(479, 'What was your first time like?', 'Sexual');
INSERT INTO Questions VALUES(480, 'Favorite type of sex: mutual masturbation, oral, vaginal, or anal?', 'Sexual');
INSERT INTO Questions VALUES(481, 'Favorite body type?', 'Sexual');
INSERT INTO Questions VALUES(482, 'Have you ever cried after sex?', 'Sexual');
INSERT INTO Questions VALUES(483, 'Could you live in a society where poly was the norm?', 'Sexual');
INSERT INTO Questions VALUES(484, 'Would/Do you use Tindr?', 'Sexual');
INSERT INTO Questions VALUES(485, 'Would you have sex with someone with both genitals?', 'Sexual');
INSERT INTO Questions VALUES(486, 'Would you ever have sex with a pregnant person/while pregnant?', 'Sexual');
INSERT INTO Questions VALUES(487, 'Thoughts on shaving your privates?', 'Sexual');
INSERT INTO Questions VALUES(488, 'Thoughts on make-up?', 'Sexual');
INSERT INTO Questions VALUES(489, 'Do you shave your genitals?', 'Sexual');
INSERT INTO Questions VALUES(490, 'If you had to replace one of your body parts with enhanced prosthetic, what part would you choose and why?', 'Sexual');
INSERT INTO Questions VALUES(491, 'Ever try/want to try thongs/lingerie?', 'Sexual');
INSERT INTO Questions VALUES(492, 'Most sensitive body part?', 'Sexual');
INSERT INTO Questions VALUES(493, 'Pad/tampon/cup?', 'Sexual');
INSERT INTO Questions VALUES(494, 'Ever tasted period blood?', 'Sexual');
INSERT INTO Questions VALUES(495, 'Would you prefer two dick-sized nipples or one nipple-sized dick?', 'Sexual');
INSERT INTO Questions VALUES(496, 'Could you live in a society that functioned without clothes?', 'Sexual');
INSERT INTO Questions VALUES(497, 'Would you want to get vajazzled/be with someone who was vajazzled?', 'Sexual');
INSERT INTO Questions VALUES(498, 'What is the best kiss you''ve ever had?', 'Sexual');
INSERT INTO Questions VALUES(499, 'Weirdest place you''ve been kissed?', 'Sexual');
INSERT INTO Questions VALUES(500, 'Do you like French kissing?', 'Sexual');
INSERT INTO Questions VALUES(501, 'Do you like Australian kissing? (It''s like French kissing, but down under)', 'Sexual');
INSERT INTO Questions VALUES(502, 'How often do you masturbate?', 'Sexual');
INSERT INTO Questions VALUES(503, 'Craziest place you''ve masturbated?', 'Sexual');
INSERT INTO Questions VALUES(504, 'Ever masturbated with someone in the same room? Did they know?', 'Sexual');
INSERT INTO Questions VALUES(505, 'What do you think about when you masturbate?', 'Sexual');
INSERT INTO Questions VALUES(506, 'Do you use porn to get yourself off?', 'Sexual');
INSERT INTO Questions VALUES(507, 'What is your favorite genre of porn?', 'Sexual');
INSERT INTO Questions VALUES(508, 'Do you remember the first time you cummed? How old were you?', 'Sexual');
INSERT INTO Questions VALUES(509, 'How did you figure out how to masturbate?', 'Sexual');
INSERT INTO Questions VALUES(510, 'Ever been turned on by your own body?', 'Sexual');
INSERT INTO Questions VALUES(511, 'Are/were you saving your virginity?', 'Sexual');
INSERT INTO Questions VALUES(512, 'Who took your virginity?', 'Sexual');
INSERT INTO Questions VALUES(513, 'Have you ever taken anyone''s virginity?', 'Sexual');
INSERT INTO Questions VALUES(514, 'How old were you when you lost your virginity?', 'Sexual');
INSERT INTO Questions VALUES(515, 'Have you ever blocked someone on social media?', 'Technology');
INSERT INTO Questions VALUES(516, 'What''s the weirdest snapchat you''ve ever received?', 'Technology');
INSERT INTO Questions VALUES(517, 'What language is your phone/social media set to right now?', 'Technology');
INSERT INTO Questions VALUES(518, 'Ever accidentally seen porn? Where and how?', 'Technology');
INSERT INTO Questions VALUES(519, 'Do you think EMF signals are dangerous?', 'Technology');
INSERT INTO Questions VALUES(520, 'What is your plan to stop a global pandemic?', 'Health');
INSERT INTO Questions VALUES(521, 'If you could go anywhere in the world, where would you go?', 'Travel');
INSERT INTO Questions VALUES(522, 'If you could change one thing about your past, what would you change?', 'Travel');
INSERT INTO Questions VALUES(523, 'If you could travel to the past/future, when would you go?', 'Travel');
INSERT INTO Questions VALUES(524, 'If you could meet somebody from any time period, who would you meet?', 'Travel');
INSERT INTO Questions VALUES(525, 'If you had to live in a different country for a year, where would you want to live?', 'Travel');
INSERT INTO Questions VALUES(526, 'If you could have dinner with anyone from any time period, what would you cook for them?', 'Travel');
INSERT INTO Questions VALUES(527, 'Which other dimension would you want to visit?', 'Travel');
INSERT INTO Questions VALUES(528, 'If you were from another planet, what planet would you be from?', 'Wildcard');
INSERT INTO Questions VALUES(529, 'What is your fatal flaw?', 'Wildcard');
INSERT INTO Questions VALUES(530, 'If you could have any superpower, what would it be?', 'Wildcard');
INSERT INTO Questions VALUES(531, 'What mythical creature do you wish were real?', 'Wildcard');
INSERT INTO Questions VALUES(532, 'If you were an animal, what animal would you be?', 'Wildcard');
INSERT INTO Questions VALUES(533, 'If you had a genie lamp, what 3 things would you wish for?', 'Wildcard');
INSERT INTO Questions VALUES(534, 'If you could have a talent (humanly possible), what would it be?', 'Wildcard');
INSERT INTO Questions VALUES(535, 'Would you want superpowers if it meant you were hunted by the government?', 'Wildcard');
INSERT INTO Questions VALUES(536, 'If you were a food/animal/plant/fungi, what type would you be?', 'Wildcard');
INSERT INTO Questions VALUES(537, 'If you were a gym leader, what type of pokemon would you specialize in?', 'Wildcard');
INSERT INTO Questions VALUES(538, '5 things somebody would put in a pentagram to summon you?', 'Wildcard');
INSERT INTO Questions VALUES(539, 'How prepared are you for a zombie apocalypse?', 'Wildcard');
INSERT INTO Questions VALUES(540, 'If you were to start a cult, what kind of weird religious hat would you make your followers wear?', 'Wildcard');
INSERT INTO Questions VALUES(541, 'If you could turn your passion into a job, what would you do?', 'Work');
INSERT INTO Questions VALUES(542, 'What job do you want to do?', 'Work');
INSERT INTO Questions VALUES(543, 'Would you do a morally unethical job for money? Ex: writing other people''s college essays for money', 'Work');
INSERT INTO Questions VALUES(544, 'Do you like your career path?', 'Work');
INSERT INTO Questions VALUES(545, 'What skills make you suitable for your career path?', 'Work');
INSERT INTO Questions VALUES(546, 'Which is more important, work or family?', 'Work');
INSERT INTO Questions VALUES(547, 'Would you give up outside hobbies to earn more at work?', 'Work');
INSERT INTO Questions VALUES(548, 'Would you ever want to be a boss?', 'Work');
INSERT INTO Questions VALUES(549, 'What roadblocks do you worry are in your career future?', 'Work');


